import {
  type Actor,
  type RecordItem,
  type Workspace,
  companies,
} from "./domain";
export const previewActor: Actor = {
  id: "preview-md",
  name: "Alex Morgan",
  role: "MD",
  companies: [...companies],
  branches: [],
};

/**
 * Preview-only sign-in accounts so each role's view can be tried without a
 * database. These are fictional and are never used by the database auth path.
 */
export const demoPassword = "demo1234";
export const demoAccounts: { email: string; actor: Actor }[] = [
  { email: "md@enercore.test", actor: previewActor },
  {
    email: "sales@enercore.test",
    actor: { id: "preview-sales", name: "Leila Ahmed", role: "Sales Manager", companies: [...companies], branches: [] },
  },
  {
    email: "hr@enercore.test",
    actor: { id: "preview-hr", name: "Priya Nair", role: "HR Manager", companies: [...companies], branches: [] },
  },
  {
    email: "accounts@enercore.test",
    actor: { id: "preview-accounts", name: "Daniel Banda", role: "Accounts Manager", companies: [...companies], branches: [] },
  },
  {
    email: "logistics@enercore.test",
    actor: { id: "preview-logistics", name: "Minh Tran", role: "Logistics Manager", companies: [...companies], branches: [] },
  },
  {
    email: "it@enercore.test",
    actor: { id: "preview-it", name: "Omar Hassan", role: "IT Administrator", companies: [...companies], branches: [] },
  },
];
export const previewActorKey = "enercore-preview-actor";
/** Reads the signed-in preview role, falling back to the default MD account. */
export function storedPreviewActor(): Actor {
  if (typeof window === "undefined") return previewActor;
  try {
    const saved = window.localStorage.getItem(previewActorKey);
    if (!saved) return previewActor;
    const parsed = JSON.parse(saved) as Actor;
    return demoAccounts.some((a) => a.actor.id === parsed.id) ? parsed : previewActor;
  } catch {
    return previewActor;
  }
}
export function makePreview(): Workspace {
  const now = new Date();
  const date = (days: number) =>
    new Date(now.getTime() + days * 86400000).toISOString().slice(0, 10);
  const rows: Partial<RecordItem>[] = [
    {
      kind: "leads",
      company: "Petronik",
      title: "Gulf Industrial Trading",
      contact: "Omar Hassan",
      product: "Base Oil · SN 500",
      quantity: 240,
      amount: 192000,
      status: "Negotiation",
      source: "Website",
      due: date(0),
    },
    {
      kind: "leads",
      company: "Afrilube",
      title: "East Africa Lubricants",
      contact: "Grace Mwangi",
      product: "Base Oil · 150N",
      quantity: 180,
      amount: 149400,
      status: "Qualified",
      source: "LinkedIn",
      due: date(1),
    },
    {
      kind: "leads",
      company: "Petronex",
      title: "Mekong Infrastructure",
      contact: "Minh Tran",
      product: "Bitumen · 60/70",
      quantity: 600,
      amount: 258000,
      status: "Quote Sent",
      source: "Referral",
      due: date(-1),
    },
    {
      kind: "leads",
      company: "Petronik",
      title: "Atlas Marine Services",
      contact: "Sarah Wilson",
      product: "Marine Lubricant",
      quantity: 75,
      amount: 97500,
      status: "New",
      source: "Website",
      due: date(2),
    },
    {
      kind: "leads",
      company: "Istanegry",
      title: "Anatolia Roadworks",
      contact: "Emre Kaya",
      product: "Bitumen · 80/100",
      quantity: 400,
      amount: 176000,
      status: "Contacted",
      source: "Trade event",
      due: date(1),
    },
    {
      kind: "leads",
      company: "Afrilube",
      title: "Copperbelt Mining",
      contact: "Daniel Banda",
      product: "Industrial Grease",
      quantity: 50,
      amount: 86000,
      status: "Won",
      source: "Distributor",
      due: date(3),
    },
    {
      kind: "quotations",
      company: "Petronik",
      title: "Gulf Industrial Trading",
      product: "Base Oil · SN 500",
      quantity: 240,
      amount: 192000,
      status: "Pending Approval",
      detail: "CFR Mombasa · 14-day validity · 30% advance",
      due: date(7),
    },
    {
      kind: "quotations",
      company: "Petronex",
      title: "Mekong Infrastructure",
      product: "Bitumen · 60/70",
      quantity: 600,
      amount: 258000,
      status: "Approved",
      due: date(10),
    },
    {
      kind: "quotations",
      company: "Afrilube",
      title: "Nairobi Distribution Co.",
      product: "Engine Oil · 15W-40",
      quantity: 80,
      amount: 112000,
      status: "Sent",
      due: date(4),
    },
    {
      kind: "orders",
      company: "Petronik",
      title: "Coastal Energy Partners",
      product: "Base Oil · 500N",
      quantity: 320,
      amount: 272000,
      status: "In Progress",
      due: date(6),
    },
    {
      kind: "orders",
      company: "Afrilube",
      title: "Copperbelt Mining",
      product: "Industrial Grease",
      quantity: 50,
      amount: 86000,
      status: "Confirmed",
      due: date(10),
    },
    {
      kind: "logistics",
      company: "Petronik",
      title: "Coastal Energy Partners",
      product: "Base Oil · 500N",
      quantity: 320,
      status: "In Transit",
      detail: "Jebel Ali → Mombasa · 16 flexitanks",
      due: date(4),
    },
    {
      kind: "logistics",
      company: "Petronex",
      title: "Pacific Trading Group",
      product: "Bitumen · 60/70",
      quantity: 400,
      status: "Delayed",
      detail: "Singapore → Ho Chi Minh City · Documents pending",
      due: date(-2),
    },
    {
      kind: "logistics",
      company: "Afrilube",
      title: "Copperbelt Mining",
      product: "Industrial Grease",
      quantity: 50,
      status: "Ready to Dispatch",
      detail: "Durban → Lusaka · 250 drums",
      due: date(7),
    },
    {
      kind: "accounts",
      company: "Petronik",
      title: "Coastal Energy Partners",
      amount: 272000,
      status: "Sent",
      due: date(12),
    },
    {
      kind: "accounts",
      company: "Afrilube",
      title: "Copperbelt Mining",
      amount: 86000,
      status: "Overdue",
      due: date(-12),
    },
    {
      kind: "accounts",
      company: "Petronex",
      title: "Pacific Trading Group",
      amount: 164000,
      status: "Paid",
      due: date(-4),
    },
    {
      kind: "customers",
      company: "Petronik",
      title: "Gulf Industrial Trading",
      contact: "Omar Hassan",
      status: "Active",
      detail: "Dubai, UAE · Net 30 · Bulk distributor",
    },
    {
      kind: "customers",
      company: "Afrilube",
      title: "East Africa Lubricants",
      contact: "Grace Mwangi",
      status: "Active",
      detail: "Nairobi, Kenya · Advance payment",
    },
    {
      kind: "products",
      company: "Petronik",
      title: "Base Oil SN 500",
      product: "Group I · Bulk / Flexitank",
      quantity: 1200,
      amount: 800,
      status: "Available",
      detail: "Viscosity grade SN 500 · USD per metric tonne",
    },
    {
      kind: "products",
      company: "Petronex",
      title: "Bitumen 60/70",
      product: "Penetration grade · Drums",
      quantity: 480,
      amount: 430,
      status: "Low Stock",
    },
    {
      kind: "products",
      company: "Afrilube",
      title: "Industrial Grease EP 2",
      product: "Lithium · 180 kg drums",
      quantity: 240,
      amount: 1720,
      status: "Available",
    },
    {
      kind: "hr",
      company: "Petronik",
      title: "Alex Morgan",
      contact: "Managing Director",
      ownerId: "preview-md",
      owner: "Alex Morgan",
      status: "Active",
      detail: "Leadership · Dubai",
    },
    {
      kind: "hr",
      company: "Petronik",
      title: "Leila Ahmed",
      contact: "Sales Manager",
      status: "Active",
      detail: "Sales · Dubai",
    },
    {
      kind: "hr",
      company: "Afrilube",
      title: "Grace Mwangi",
      contact: "Account Executive",
      status: "On Leave",
      detail: "Sales · Nairobi",
    },
    {
      kind: "leave",
      company: "Petronik",
      title: "Leila Ahmed · Annual leave",
      quantity: 3,
      status: "Pending Approval",
      due: date(14),
      detail: "3 working days · Annual leave",
    },
    {
      kind: "marketing",
      company: "Petronik",
      title: "Base oils · Q4 outreach",
      product: "LinkedIn",
      amount: 4500,
      quantity: 38,
      status: "Active",
      detail: "38 leads · Campaign budget USD 4,500",
    },
    {
      kind: "marketing",
      company: "Afrilube",
      title: "Africa distributor programme",
      product: "Website",
      amount: 2800,
      quantity: 24,
      status: "Active",
    },
    {
      kind: "it",
      company: "Petronik",
      title: "Email access on new laptop",
      contact: "Leila Ahmed",
      status: "Open",
      detail: "Access request · Medium priority",
      due: date(1),
    },
    {
      kind: "it",
      company: "Petronex",
      title: "Renew design software licence",
      status: "In Progress",
      detail: "Software · Normal priority",
      due: date(8),
    },
  ];
  const records = rows.map(
    (r, i) =>
      ({
        id: `EC-${String(1001 + i)}`,
        kind: "leads",
        company: "Petronik",
        branch: "Main",
        title: "",
        contact: "",
        product: "",
        quantity: 0,
        unit: "MT",
        amount: 0,
        currency: "USD",
        status: "New",
        ownerId: "preview-sales",
        owner: "Leila Ahmed",
        due: date(7),
        detail: "",
        source: "Manual",
        createdAt: date(-10) + "T09:00:00.000Z",
        updatedAt: now.toISOString(),
        ...r,
      }) as RecordItem,
  );
  return {
    records,
    audit: records
      .slice(0, 5)
      .map((r, i) => ({
        id: `a${i}`,
        actor: r.owner,
        action: `Created ${r.kind === "leads" ? "lead" : r.kind}`,
        recordId: r.id,
        company: r.company,
        at: new Date(now.getTime() - i * 3600000).toISOString(),
      })),
  };
}
