import type { Module } from "./domain";

export type PageHelp = { purpose: string; steps: string[] };
export const moduleHelp: Record<Module, PageHelp> = {
  overview: { purpose: "A summary of the business you have access to.", steps: ["Choose a company and time period.", "Review figures and items needing attention.", "Open a record to see its details before taking action."] },
  leads: { purpose: "A lead is a possible sale: someone asking about a product.", steps: ["Add the customer and what they need.", "Set your next follow-up and record the conversation.", "Prepare a quotation when you know what to offer."] },
  quotations: { purpose: "A quotation is a price offer for your customer, not a confirmed sale.", steps: ["Choose the customer and add items and prices.", "Check the details and follow the approval process.", "Record acceptance to start the existing order handover; do not re-enter the same sale."] },
  orders: { purpose: "Sales orders show confirmed customer purchases.", steps: ["Open an order to check its products and agreed values.", "Use its linked shipment and invoice for delivery and payment.", "Update progress instead of creating duplicate records."] },
  logistics: { purpose: "Track where a delivery is and when it should arrive.", steps: ["Open the shipment linked to the order.", "Check the destination and expected delivery date.", "Record progress and any delivery problems."] },
  accounts: { purpose: "Keep track of customer invoices and company money received or spent.", steps: ["Use invoices for customer payments.", "Use income or expense entries for other company transactions.", "Do not record the same invoice payment again in the cashbook."] },
  customers: { purpose: "Customers are the people or companies you sell to.", steps: ["Search before adding a customer.", "Open a customer to see contacts and related sales.", "Start new work from that customer to reuse their details."] },
  suppliers: { purpose: "Suppliers are the companies you buy products from.", steps: ["Search before adding a supplier.", "Record the products they can supply.", "Use sourcing tools when you need to request or compare an offer."] },
  products: { purpose: "Your product list keeps names, grades and selling units consistent.", steps: ["Find a product or add a missing one.", "Check its grade and unit.", "Select it when preparing a quotation to reuse available details."] },
  hr: { purpose: "Employee details and leave requests, in one place.", steps: ["Add or open an employee profile.", "Keep job and salary details up to date.", "Review leave requests. An employee record does not create a login."] },
  marketing: { purpose: "Plan and track activities that bring in new enquiries.", steps: ["Create a campaign with a name and channel.", "Add a budget or audience when known.", "Update results as the campaign progresses."] },
  it: { purpose: "Ask for help with computers, software or access.", steps: ["Describe the problem in a short title.", "Choose how urgent it is and add useful details.", "Follow the ticket for updates from IT."] },
  approvals: { purpose: "Requests that need an authorized person's decision.", steps: ["Open the request and check its details.", "Approve or reject only after reviewing it.", "The existing approval rules decide what happens next."] },
  activity: { purpose: "A history of who changed what and when.", steps: ["Use filters to find the relevant work.", "Review the recorded change and its author.", "Open the related record for more context."] },
  settings: { purpose: "Workspace configuration for the companies you can manage.", steps: ["Choose the setting you need to change.", "Review the existing value before editing.", "Save only changes you are authorized to make."] },
};

export const viewHelp: Record<string, string> = {
  actions: "Your follow-ups, reminders and work needing attention.",
  prospecting: "Find potential customers. Review matches before importing; provider searches or enrichment may use credits.",
  collaboration: "Team conversations and work shared with you.",
  ai: "Ask for assistance with work you can access. Review suggestions; AI does not approve or send work for you.",
  access: "Manage who can sign in and which companies and modules they can use.",
};

export const pageGuides: Record<string, PageHelp> = {
  "My profile": { purpose: "Your personal details and workspace preferences.", steps: ["Check your name and contact details.", "Update the preferences available to you.", "Company access is managed by an authorized administrator."] },
  "Appearance": { purpose: "Make the workspace comfortable to read.", steps: ["Choose light or dark mode.", "Choose your preferred colour palette.", "These choices affect your display, not company records."] },
  "Access control": { purpose: viewHelp.access, steps: ["Choose the user you want to manage.", "Review their role, company access and module permissions.", "Save carefully: permissions control what the user can see and change."] },
  "Prospecting": { purpose: viewHelp.prospecting, steps: ["Describe the type of customer you want to find.", "Review the search criteria and any credit notice before searching.", "Check a result before importing it; do not create duplicate customers."] },
  "Notifications": { purpose: "Updates and reminders relevant to your work.", steps: ["Open an update to see its related work.", "Mark items as read once checked.", "Reading a notification does not approve or complete the underlying request."] },
  "My requests": { purpose: "Your leave and other personal requests.", steps: ["Choose the type of request you need.", "Fill in the essentials and submit it.", "Return here to check the decision or progress."] },
  "Collaboration": { purpose: viewHelp.collaboration, steps: ["Open the relevant conversation.", "Share an update with the right people.", "Use the linked record for official status and commercial changes."] },
  "Action Center": { purpose: viewHelp.actions, steps: ["Start with overdue or urgent work.", "Open the item to understand what needs doing.", "Record the result and your next follow-up."] },
  "Enercore AI": { purpose: viewHelp.ai, steps: ["Ask a specific question about your work.", "Check the sources and figures in the answer.", "Make business decisions through the normal approval workflow."] },
};

// Label-based help works across existing forms without changing their schemas.
export const fieldHelp: Record<string, string> = {
  "Business entity": "The company this record belongs to. Choose the company doing this business, not the customer's company.",
  "Customer / company": "The customer asking about a product. Use an existing customer when available to avoid duplicates.",
  "Customer / Company": "The customer receiving this price offer. Check that the correct company is selected.",
  "Product needed": "What the customer is asking for, including the grade if known. Other details can be added later.",
  "Product / Grade": "The product and its specification, for example Base Oil SN 500.",
  "Grade / Specification": "The specification that distinguishes this product from similar products.",
  "Next follow-up": "The date you plan to contact the customer again. It is not the delivery date.",
  "Estimated value": "An estimate of the possible sale. This is not money received.",
  "Order value": "The agreed total value of the order, in the selected currency.",
  "Currency": "The currency used for these amounts. Check it before entering prices; changing it does not convert money.",
  "Unit": "How quantity is measured. MT means metric tonnes. Keep the unit consistent with the quoted price.",
  "Quantity": "How much is needed, measured in the selected unit.",
  "Unit price": "Price for one selected unit. The item total is quantity multiplied by this price.",
  "Packaging / Unit": "How the item is packed, such as drums or bulk. This does not convert the quantity unit.",
  "Valid until": "The last date this quotation is valid. Review it before sending the offer.",
  "Issue date": "The date printed on the quotation. Validity must be on or after this date.",
  "Sender legal name": "The legal name of your selling company, printed on the quotation.",
  "Sender address": "Your selling company's address, printed on the quotation.",
  "Customer address": "The customer's billing or business address for this quotation.",
  "Sender tax / TRN number": "Your company's tax registration number, if applicable. Do not enter the customer's number here.",
  "Customer tax / TRN number": "The customer's tax registration number, if applicable.",
  "Incoterm": "The agreed delivery term, such as FOB or CIF, defining delivery responsibilities. Confirm the term before using it.",
  "Payment terms": "When and how payment is due, for example advance payment or agreed credit terms.",
  "Destination / Port": "Where the goods should be delivered. Add the destination country separately when known.",
  "Destination country": "The delivery country. This also helps the dashboard group sales by country.",
  "Lead source": "How this enquiry reached you, such as email, a referral or the website.",
  "Contact person": "The person to speak to at the customer's or supplier's company.",
  "Quotation reference": "An optional reference to show on the quotation. The CRM keeps its own record ID.",
  "Amount in words (calculated)": "Generated automatically from the quotation total. You do not need to type it.",
  "Basic salary": "The fixed salary amount, excluding allowance. Monthly total is calculated from the two amounts.",
  "Allowance": "The allowance amount added to basic salary, in the selected salary currency.",
  "Employee role": "The person's work role. This does not grant application permissions or create a login.",
  "Work arrangement": "Whether the person works on-site or remotely.",
  "Entry type": "Choose Expense for money spent or Income for money received. Do not duplicate an invoice payment here.",
  "Payment method": "How the money was actually paid or received, such as bank transfer or cash.",
  "Priority": "How urgently help is needed. Use urgent only for work that cannot wait.",
  "Working days": "The number of working days requested, not the number of calendar days.",
  "Recorded stock quantity": "A recorded quantity, not a guarantee of available stock. Confirm availability before promising delivery.",
  "Indicative unit price": "A reference price for one unit. Confirm current pricing before making an offer.",
  "Salary currency": "The currency for basic salary and allowance. Changing this choice does not convert the amounts.",
  "Authorized signatory name": "The authorized person's name printed on the document. This field is not an electronic approval.",
  "Authorized signatory title": "The authorized person's job title, printed below their name.",
  "Country": "The country where this company is based. Use the full country name when known.",
  "Main contact": "The person you normally speak to at this company.",
  "Company name": "The business name. Search existing records first to avoid creating a duplicate.",
  "Products supplied": "Products this supplier can potentially supply. Confirm price and availability separately.",
  "Products of interest": "Products the customer is interested in buying. This is not a confirmed order.",
  "Billing address": "The address to use for billing documents for this customer.",
  "Agreed payment terms": "The payment arrangement agreed with this customer, subject to any required approval.",
  "Typical lead time": "How long the supplier usually takes to prepare delivery. Confirm the actual timing for each order.",
  "SKU / Product code": "An optional internal code that helps identify this product.",
  "Employee ID": "Your company's employee reference, if one has already been assigned.",
  "Joining date": "The date the employee starts or started working for the company.",
  "Requested by": "The person who needs help. Your own name is filled in when available.",
  "Needed by": "The date help is needed. Choose priority separately to show urgency.",
  "Affected device / Application": "Which computer, device or application has the problem.",
  "Planned budget": "The expected campaign spending, not the amount actually spent.",
  "Lead target": "How many customer enquiries you hope the campaign will generate.",
  "Target audience": "The people or companies this campaign is intended to reach.",
  "Required by": "The date the customer needs the order. Check the agreed delivery arrangements.",
  "Expected delivery": "The latest expected arrival date. Update it if the shipment is delayed.",
  "Payment due": "The date payment is expected according to the agreed terms.",
  "Transaction date": "The date the money was received or spent, not necessarily today's date.",
  "Receipt / Bank reference": "A reference that helps match this entry to its receipt or bank transaction.",
  "Paid to / Received from": "The person or company on the other side of this payment.",
};
