import { test, expect } from "@playwright/test";
import { Client } from "./client";

test('content plans save, survive reload, edit and delete with confirmation', async ({browser}) => {
  const client = await Client.login('cmmd');
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  await client.signInBrowser(context);
  const page = await context.newPage();
  await page.goto('/workspace/all-companies/marketing');
  await page.getByRole('button',{name:'Plan a post',exact:true}).click();
  const title = `Calendar check ${crypto.randomUUID().slice(0,8)}`;
  await page.getByRole('textbox',{name:'Post title',exact:true}).fill(title);
  await page.getByRole('textbox',{name:'Caption / content notes',exact:true}).fill('Fictional local content plan.');
  await page.getByRole('button',{name:'Save post plan',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.reload();
  await expect(page.locator('.content-grid .content-post').filter({hasText:title})).toBeVisible();
  await page.locator('.content-calendar').screenshot({path:'test-results/content-calendar-desktop.png'});
  await page.locator('.content-grid .content-post').filter({hasText:title}).click();
  await page.getByRole('textbox',{name:'Caption / content notes',exact:true}).fill('Updated caption');
  await page.getByRole('button',{name:'Save post plan',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('.content-calendar').screenshot({path:'test-results/content-calendar-phone.png'});
  await page.locator('.content-agenda .content-post').filter({hasText:title}).click();
  await expect(page.getByRole('textbox',{name:'Caption / content notes',exact:true})).toHaveValue('Updated caption');
  await page.getByRole('button',{name:'Delete post',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Delete record?'})).toBeVisible();
  await page.getByRole('button',{name:'Delete record',exact:true}).click();
  await expect(page.locator('.content-agenda .content-post').filter({hasText:title})).toHaveCount(0);
  await context.close();
});

test("mail is private even from MD; captures are confirmed and idempotent", async () => {
  const owner = await Client.login("cmsales");
  const other = await Client.login("cmsales2");
  const md = await Client.login("cmmd");
  const draft = { id: crypto.randomUUID(), to: "buyer@example.invalid", subject: `Private ${crypto.randomUUID()}`, body: "Local only" };
  expect((await owner.request("GET", "/api/mail", undefined, { cookie: null })).status).toBe(401);
  expect((await owner.request("POST", "/api/mail/analyze", { id: draft.id })).status).toBe(404);
  expect((await owner.request("POST", "/api/mail/analyze", { id: draft.id, ownerId:other.id })).status).toBe(400);
  expect((await owner.request("POST", "/api/mail", { ...draft, action: "save" }, { origin: "https://example.invalid" })).status).toBe(403);
  expect((await owner.request("POST", "/api/mail", { ...draft, action: "save", ownerId: other.id })).status).toBe(400);
  expect((await owner.request("POST", "/api/mail", { ...draft, action: "save" })).status).toBe(200);
  for (const outsider of [other, md]) {
    const result = await outsider.request("GET", `/api/mail?ownerId=${owner.id}`);
    expect(result.status).toBe(200);
    expect(JSON.stringify(result.body)).not.toContain(draft.subject);
  }
  expect((await owner.request("POST", "/api/mail", { ...draft, action: "send-test" })).status).toBe(400);
  for (let i = 0; i < 2; i++) expect((await owner.request("POST", "/api/mail", { ...draft, action: "send-test", confirmed: true })).body.delivery).toBe("captured-locally-not-delivered");
  const result = await owner.request("GET", "/api/mail");
  expect(result.body.messages.filter((m: { id: string }) => m.id === draft.id)).toHaveLength(1);
  expect(result.body.messages.find((m: { id: string }) => m.id === draft.id).folder).toBe("outbox");
});

test("local email compose and collaboration work on desktop and phone", async ({ browser }) => {
  const client = await Client.login("pg35");
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  await client.signInBrowser(context);
  const page = await context.newPage();
  const subject = `Local browser test ${crypto.randomUUID().slice(0, 8)}`;
  await page.goto("/workspace/all-companies/email");
  await expect(page.getByText("Local test inbox", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: /Sample enquiry: Base Oil/ }).click();
  await page.getByRole("button", { name: "Analyse email", exact: true }).click();
  await expect(page.getByText("Local simulation · not a live AI result")).toBeVisible();
  await page.locator(".mail-intake").screenshot({path:"test-results/mail-intake-review.png",animations:"disabled"});
  await expect(page.getByRole("button", { name: "Review lead", exact:true })).toBeDisabled();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Review lead", exact:true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Close dialog", exact:true }).click();
  await page.getByRole("button", { name: "Social channels", exact:true }).click();
  await page.screenshot({path:"test-results/social-channels.png",animations:"disabled"});
  await page.getByRole("article").filter({ has:page.getByRole("heading", { name:"WhatsApp Business",exact:true }) }).getByRole("button",{name:"View setup"}).click();
  await page.getByRole("button", { name:"Try local conversation" }).click();
  await page.getByRole("textbox",{name:"Reply",exact:true}).fill("Local test reply only");
  await page.getByRole("button",{name:"Capture test reply"}).click();
  await expect(page.getByText("Local test reply only",{exact:true})).toBeVisible();
  await expect(page.getByText(/Captured locally, not delivered/)).toBeVisible();
  await page.screenshot({path:"test-results/social-conversation-desktop.png",animations:"disabled"});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole("button",{name:"Capture test reply"})).toBeInViewport();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:"test-results/social-conversation-phone.png",animations:"disabled"});
  await page.setViewportSize({width:1440,height:900});
  await page.getByRole("button",{name:"Close demo"}).click();
  await page.getByRole("button",{name:"Email workspace",exact:true}).click();
  await page.getByRole("button", { name: "New email", exact: true }).click();
  await page.getByRole("textbox", { name: "To", exact: true }).fill("buyer@example.invalid");
  await page.getByRole("textbox", { name: "Subject", exact: true }).fill(subject);
  await page.getByRole("textbox", { name: "Message", exact: true }).fill("Not sent externally.");
  const dialog = page.getByRole("dialog");
  await expect(dialog.locator(".ui-dialog-footer").getByRole("button", { name: "Review test email" })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Close", exact: true })).toHaveCount(0);
  await page.screenshot({ path: "test-results/mail-compose-desktop.png", animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dialog.locator(".ui-dialog-footer").getByRole("button", { name: "Save draft" })).toBeInViewport();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/mail-compose-phone.png", animations: "disabled" });
  await page.evaluate(() => document.documentElement.dataset.theme = "dark");
  await page.screenshot({ path: "test-results/mail-compose-dark.png", animations: "disabled" });
  await page.evaluate(() => document.documentElement.dataset.theme = "light");
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole("button", { name: "Review test email", exact: true }).click();
  await page.getByRole("button", { name: "Confirm test send", exact: true }).click();
  await expect(page.getByText("Captured in the test outbox. No real email was sent.")).toBeVisible();
  await page.getByRole("button", { name: new RegExp(subject) }).click();
  await page.screenshot({ path: "test-results/local-mail-desktop.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/local-mail-phone.png" });
  await page.goto("/workspace/all-companies/collaboration");
  await page.setViewportSize({width:1440,height:900});
  await expect(page.locator(".collab-refined")).toBeVisible();
  await page.screenshot({path:"test-results/collaboration-refined.png",animations:"disabled"});
  await expect(page.locator(".collab-unavailable")).toHaveCount(0);
  expect((await client.get("/conversations")).status).toBe(200);
  const room = await client.createRoom({ name: "Local email phase review", members: ["pg36"] });
  expect((await client.send(room.id, "Collaboration works locally.")).status).toBe(201);
  const colleague = await Client.login("pg36");
  expect(JSON.stringify((await colleague.page(room.id)).body)).toContain("Collaboration works locally.");
  await context.close();
});
