/**
 * Worker entry point.
 *
 * Wraps the handler that `opennextjs-cloudflare build` generates in
 * .open-next/worker.js (the OpenNext "custom worker" pattern) so the
 * Collaboration Hub can add what Next.js route handlers cannot provide:
 *
 * - the realtime socket at /api/collab/socket, authenticated here and handed
 *   to the caller's own CollabHub Durable Object;
 * - the CollabHub Durable Object class itself.
 *
 * Every other request goes to OpenNext unchanged, and its own Durable Object
 * classes are re-exported unchanged.
 */

// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before a build.
import openNext from "./.open-next/worker.js";
import { collabSocket, type GatewayEnv } from "./src/realtime/gateway";

// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before a build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
export { CollabHub } from "./src/realtime/collab-hub";

type Handler = { fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> };

export default {
  async fetch(request: Request, env: GatewayEnv, ctx: unknown) {
    if (new URL(request.url).pathname === "/api/collab/socket") return collabSocket(request, env);
    return (openNext as Handler).fetch(request, env, ctx);
  },
};
