/**
 * Worker entry point.
 *
 * Wraps the handler that `opennextjs-cloudflare build` generates in
 * .open-next/worker.js (the OpenNext "custom worker" pattern) so the
 * Collaboration Hub can add what Next.js route handlers cannot provide:
 *
 * - the realtime socket at /api/collab/socket, authenticated here and handed
 *   to the caller's own CollabHub Durable Object;
 * - Collaboration files and room images, authorised here and streamed from
 *   R2 with exactly the headers they need;
 * - the daily retention purge of deleted/unsent attachments and old sign-ins
 *   (expired sessions and refresh tokens), and the daily
 *   notification reminders (follow-ups, expiring quotations, overdue items);
 * - every five minutes, meeting reminders and closing abandoned meetings;
 * - the CollabHub Durable Object class itself.
 *
 * Every other request goes to OpenNext unchanged, and its own Durable Object
 * classes are re-exported unchanged.
 */

// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before a build.
import openNext from "./.open-next/worker.js";
import { collabSocket, type GatewayEnv } from "./src/realtime/gateway";
import { collabFile, purgeAttachments, roomAvatar, type FilesEnv } from "./src/realtime/files";
import { purgeSignIns } from "./src/realtime/auth-purge";
import { REMINDER_CRON, runReminders } from "./src/realtime/reminders";
import { MEETING_CRON, runMeetingSweep } from "./src/realtime/meeting-sweep";

// @ts-ignore -- generated by `opennextjs-cloudflare build`; absent before a build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
export { CollabHub } from "./src/realtime/collab-hub";

type Handler = { fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> };
type Env = GatewayEnv & FilesEnv;
type Ctx = { waitUntil(promise: Promise<unknown>): void };

const FILE = /^\/api\/collab\/files\/([^/]+)$/;
const AVATAR = /^\/api\/collab\/rooms\/([^/]+)\/avatar$/;

export default {
  async fetch(request: Request, env: Env, ctx: unknown) {
    const path = new URL(request.url).pathname;
    if (path === "/api/collab/socket") return collabSocket(request, env);
    const file = FILE.exec(path);
    if (file) return collabFile(request, env, file[1]);
    const avatar = AVATAR.exec(path);
    if (avatar) return roomAvatar(request, env, avatar[1]);
    return (openNext as Handler).fetch(request, env, ctx);
  },
  async scheduled(controller: { cron?: string }, env: Env, ctx: Ctx) {
    if (controller.cron === REMINDER_CRON) ctx.waitUntil(runReminders(env));
    else if (controller.cron === MEETING_CRON) ctx.waitUntil(runMeetingSweep(env as never));
    else ctx.waitUntil(Promise.all([purgeAttachments(env), purgeSignIns(env as never)]));
  },
};
