import { test, expect } from "@playwright/test";
test("add and cancel a company expense, preserve invoice separation", async ({page}, info) => {
  await page.goto("/?module=accounts&company=Petronik");
  await page.getByRole("button",{name:"Add entry",exact:true}).click();
  await page.getByRole("textbox",{name:"Description",exact:true}).fill("Office supplies QA");
  await page.getByRole("spinbutton",{name:"Amount",exact:true}).fill("125.50");
  await page.getByRole("button",{name:"Save record",exact:true}).click();
  await expect(page.getByRole("dialog")).toBeHidden();
  await expect(page.locator(".cashbook-summary")).toContainText("$125.50");
  await page.getByRole("button",{name:/Office supplies QA/}).click();
  await expect(page.getByText("Expense entry",{exact:false})).toBeVisible();
  await page.getByRole("combobox",{name:"Update status"}).click();
  await page.getByRole("option",{name:"Cancelled",exact:true}).click();
  await page.getByRole("button",{name:"Close",exact:true}).click();
  await expect(page.locator(".cashbook-summary")).not.toContainText("$125.50");
  await page.reload();
  await expect(page.locator(".cashbook-panel")).toContainText("Office supplies QA");
  await page.getByRole("button",{name:"Add entry",exact:true}).click();
  await page.getByRole("textbox",{name:"Description",exact:true}).fill("Other income QA");
  await page.getByRole("combobox",{name:"Entry type",exact:true}).click();
  await page.getByRole("option",{name:"Income",exact:true}).click();
  await page.getByRole("spinbutton",{name:"Amount",exact:true}).fill("250");
  await page.getByRole("button",{name:"Save record",exact:true}).click();
  await expect(page.getByRole("dialog")).toBeHidden();
  await expect(page.locator(".cashbook-summary")).toContainText("$250.00");
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:info.outputPath("accounts-mobile.png"),animations:"disabled"});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
