/** Answer sections of the Sales Copilot — shared by the server schema and the UI. */

export const SECTION_KEYS = [
  "situation",
  "requirement",
  "developments",
  "commercial",
  "risks",
  "relationship",
  "opportunities",
  "meetings",
  "quotations",
  "orders",
  "products",
  "open_actions",
  "timeline",
  "objective",
  "known",
  "gaps",
  "recent_activity",
  "what_happened",
  "decisions",
  "requirements_mentioned",
  "action_items",
] as const;
export type SectionKey = (typeof SECTION_KEYS)[number];

export const SECTION_TITLES: Record<SectionKey, string> = {
  situation: "Current situation",
  requirement: "Customer requirement",
  developments: "Recent developments",
  commercial: "Commercial information",
  risks: "Risks",
  relationship: "Relationship summary",
  opportunities: "Current opportunities",
  meetings: "Recent meetings",
  quotations: "Open quotations",
  orders: "Orders",
  products: "Products discussed",
  open_actions: "Open actions",
  timeline: "Recent timeline",
  objective: "Meeting objective",
  known: "What we know",
  gaps: "Commercial gaps",
  recent_activity: "Recent activity",
  what_happened: "What happened",
  decisions: "Decisions",
  requirements_mentioned: "Requirements mentioned",
  action_items: "Action items",
};
