"use client";
import { useState } from 'react';
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import { PageHeader, FormGrid } from './ui/layout';
import { Button, Dialog, DialogActions, Field, Input, Select, Textarea } from './ui/controls';
import { canWrite, type Actor, type RecordItem } from '@/lib/domain';
import { companyName } from '@/lib/company-name';
import { calendarDays, contentChannels, contentStages, contentFormats, contentError, isContentPost } from '@/lib/content-calendar';
export type ContentValues = Omit<RecordItem, 'id' | 'status' | 'ownerId' | 'owner' | 'createdAt' | 'updatedAt'>;
export default function ContentCalendar({records, actor, company, onSave, onDelete, onCampaign, onCompany}: {records: RecordItem[]; actor: Actor; company: string; onSave: (values: ContentValues, existing: RecordItem | null, requestId: string) => Promise<void>; onDelete: (r: RecordItem) => void; onCampaign:()=>void; onCompany:(company:string)=>void}) {
  const today = new Intl.DateTimeFormat('en-CA', {timeZone:'Asia/Dubai', year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const [month,setMonth] = useState(today.slice(0,7));
  const [channel,setChannel] = useState('All channels'); const [stage,setStage] = useState('All stages');
  const [mode,setMode] = useState('Month'); const [query,setQuery] = useState('');
  const [editor,setEditor] = useState<{record:RecordItem|null; date:string; key:string}|null>(null);
  const entity = company === 'All companies' ? actor.companies[0] : company;
  const writable = canWrite(actor, {kind:'marketing',company:entity,branch:actor.branches[0] || 'Main',ownerId:actor.id} as RecordItem);
  const posts = records.filter(r => isContentPost(r) && !r.deletedAt && r.due.startsWith(month) && (channel === 'All channels' || r.product === channel) && (stage === 'All stages' || r.attributes?.contentStage === stage) && `${r.title} ${r.detail}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => `${a.due}${a.attributes?.contentTime || ''}`.localeCompare(`${b.due}${b.attributes?.contentTime || ''}`));
  function move(delta:number) { const d = new Date(`${month}-01T12:00:00Z`); d.setUTCMonth(d.getUTCMonth()+delta); setMonth(d.toISOString().slice(0,7)); }
  const open = (record:RecordItem|null, date=today) => setEditor({record,date,key:crypto.randomUUID()});
  const postButton = (r:RecordItem) => <button key={r.id} className="content-post" onClick={() => open(r)}><span>{r.product} · {r.attributes?.contentTime || 'Time not set'}</span><strong>{r.title}</strong><small>{r.attributes?.contentStage} · {companyName(r.company)}</small></button>;
  return <section className="content-calendar" aria-label="Content calendar"><PageHeader title="Content calendar" description="Plan your social content, from first idea to ready to post." actions={<div className="heading-actions">{writable && <><Button className="secondary" onClick={onCampaign}>New campaign</Button><Button className="primary" onClick={() => open(null)}><Plus size={16}/>Plan a post</Button></>}</div>}/>
    <div className="content-toolbar"><div className="content-month"><Button className="secondary" aria-label="Previous month" onClick={() => move(-1)}><ChevronLeft size={16}/></Button><strong>{new Date(`${month}-01T12:00:00Z`).toLocaleDateString('en',{month:'long',year:'numeric',timeZone:'UTC'})}</strong><Button className="secondary" aria-label="Next month" onClick={() => move(1)}><ChevronRight size={16}/></Button><Button className="secondary" onClick={() => setMonth(today.slice(0,7))}>This month</Button></div><Select aria-label="Calendar view" value={mode} onChange={e => setMode(e.target.value)}><option>Month</option><option>List</option></Select></div>
    <div className="content-filters"><Input aria-label="Search content" placeholder="Search posts or captions…" value={query} onChange={e => setQuery(e.target.value)}/>{actor.companies.length>1 && <Select aria-label="Content company" value={company} onChange={e=>onCompany(e.target.value)}><option>All companies</option>{actor.companies.map(c=><option key={c} value={c}>{companyName(c)}</option>)}</Select>}<Select aria-label="Filter channel" value={channel} onChange={e=>setChannel(e.target.value)}>{['All channels',...contentChannels].map(v=><option key={v}>{v}</option>)}</Select><Select aria-label="Filter stage" value={stage} onChange={e=>setStage(e.target.value)}>{['All stages',...contentStages].map(v=><option key={v}>{v}</option>)}</Select></div><div className="content-caption"><span>{posts.length} {posts.length===1?'post':'posts'} · Dubai time (GST)</span><span>Planning only · publish manually in each app</span></div>
    {mode === 'Month' && <div className="content-grid-wrap"><div className="content-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><div className="content-weekday" key={d}>{d}</div>)}{calendarDays(month).map((d,i)=><div className={`content-day ${d === today ? 'is-today' : ''} ${!d ? 'is-outside' : ''}`} key={d || i}>{d && <><div className="content-day-heading"><span>{Number(d.slice(-2))}</span>{writable && <button aria-label={`Plan post for ${d}`} onClick={()=>open(null,d)}><Plus size={14}/></button>}</div>{posts.filter(r=>r.due === d).map(postButton)}</>}</div>)}</div></div>}
    <div className={`content-agenda ${mode === 'Month' ? 'mobile-agenda' : ''}`}>{posts.map(r=><div key={r.id}><time>{r.due}</time>{postButton(r)}</div>)}</div>
    {!posts.length && <p className="content-empty">No posts match this month. Plan your first post or change the filters.</p>}
    {editor && <PostEditor key={editor.key} existing={editor.record} date={editor.date} entity={entity} actor={actor} requestId={editor.key} onSave={onSave} onClose={()=>setEditor(null)} onDelete={r=>{setEditor(null);onDelete(r);}}/>}
  </section>;
}
function PostEditor({existing,date,entity,actor,requestId,onSave,onClose,onDelete}:{existing:RecordItem|null;date:string;entity:string;actor:Actor;requestId:string;onSave:(v:ContentValues,r:RecordItem|null,k:string)=>Promise<void>;onClose:()=>void;onDelete:(r:RecordItem)=>void}) {
  const [v,setV] = useState<ContentValues>(existing ? {...existing} : {kind:'marketing',company:entity,branch:actor.branches[0] || 'Main',title:'',contact:'',product:'Instagram',quantity:0,unit:'posts',amount:0,currency:'USD',due:date,detail:'',source:'Content calendar',attributes:{contentType:'social-post',contentStage:'Idea',contentFormat:'Image',contentTime:'',contentTimezone:'Asia/Dubai',contentAsset:''}});
  const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const editable=canWrite(actor, existing || {...v,ownerId:actor.id} as RecordItem);
  const attr=(key:string,value:string)=>setV({...v,attributes:{...v.attributes,[key]:value}});
  async function save(){ const problem=contentError(v); if(problem){setError(problem);return;} setBusy(true);setError('');try{await onSave(v,existing,requestId);onClose();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Try again.');}finally{setBusy(false);}}
  return <Dialog title={existing?'Post plan':'Plan a post'} description="Organise your content. No automatic publishing." onClose={()=>{if(!busy)onClose();}}><fieldset disabled={busy || !editable} className="content-form"><Field>Post title<Input value={v.title} maxLength={160} placeholder="e.g. SN 500 product spotlight" onChange={e=>setV({...v,title:e.target.value})}/></Field><FormGrid><Field>Company<Select disabled={!!existing} value={v.company} onChange={e=>setV({...v,company:e.target.value})}>{actor.companies.map(c=><option key={c} value={c}>{companyName(c)}</option>)}</Select></Field><Field>Channel<Select value={v.product} onChange={e=>setV({...v,product:e.target.value})}>{contentChannels.map(c=><option key={c}>{c}</option>)}</Select></Field><Field>Planned date<Input type="date" value={v.due} onChange={e=>setV({...v,due:e.target.value})}/></Field><Field>Time · Dubai (optional)<Input type="time" value={v.attributes?.contentTime || ''} onChange={e=>attr('contentTime',e.target.value)}/></Field><Field>Format<Select value={v.attributes?.contentFormat} onChange={e=>attr('contentFormat',e.target.value)}>{contentFormats.map(c=><option key={c}>{c}</option>)}</Select></Field><Field>Planning stage<Select value={v.attributes?.contentStage} onChange={e=>attr('contentStage',e.target.value)}>{contentStages.map(c=><option key={c}>{c}</option>)}</Select></Field></FormGrid><Field>Caption / content notes<Textarea rows={4} maxLength={5000} value={v.detail} onChange={e=>setV({...v,detail:e.target.value})}/></Field><Field>Design or video link (optional)<Input type="url" placeholder="https://…" maxLength={300} value={v.attributes?.contentAsset || ''} onChange={e=>attr('contentAsset',e.target.value)}/></Field><small>“Published manually” is your own record, not confirmation from a social platform.</small></fieldset>{error && <p role="alert" className="error">{error}</p>}<DialogActions pending={busy} start={existing && editable ? <Button className="danger" disabled={busy} onClick={()=>onDelete(existing)}>Delete post</Button>:undefined} primary={editable?{label:'Save post plan',pending:busy,onClick:save}:undefined}/></Dialog>;
}
